// Демо-каталог роботизированных решений (ТЗ 3.3). Стоимости — ориентировочные
// допущения для хакатон-демо (ТЗ 7.5), не реальные прайсы вендоров; у каждой
// позиции есть source с пометкой "demo-assumption" для честности перед жюри (ТЗ 3.3.4).
//
// Поля сгруппированы по табл. 3.3.7: identification / technical / infra / economics /
// applicability / dataQuality.
//
// economics.infrastructureCost/commissioningCost/trainingCost — статьи CAPEX
// из ТЗ 3.5.2, которых раньше в каталоге не было (учитывались только equipment/
// software/implementation, CAPEX был занижен). Заданы на робота и, как и
// остальные позиции экономики, умножаются на количество — упрощение: в жизни
// зарядные станции и обучение персонала масштабируются с флотом не совсем
// линейно (эффект масштаба), но для экспресс-оценки этого достаточно.

export const CATALOG = [
  {
    id: "vac-lite",
    identification: {
      vendor: "CleanBot",
      name: "CleanBot Lite 500",
      type: "vacuum",
      purpose: "Автономная уборка складских полов",
      country: "РФ",
      availability: "в наличии",
    },
    technical: {
      throughput: 1800,
      throughputUnit: "м²/ч",
      speed: 1.1,
      autonomyHours: 4,
      energy: { workPowerKw: 0.4, idlePowerKw: 0.02, chargeHours: 1.5 },
      positioningAccuracyMm: 50,
      navigationType: "LIDAR + SLAM",
    },
    infra: {
      floorRequirement: "ровный пол, уклон < 2%",
      chargingStations: 1,
    },
    economics: {
      equipmentCost: 950000,
      infrastructureCost: 80000,
      softwareCost: 40000,
      implementationCost: 60000,
      commissioningCost: 20000,
      trainingCost: 10000,
      maintenanceCostPerYear: 85000,
      serviceCostPerYear: 45000,
      lifespanYears: 5,
      raas: { monthlyRate: 42000, contractMonths: 24, buyoutOption: true },
    },
    applicability: {
      objectTypes: ["warehouse"],
      processes: ["floor_cleaning"],
      limitations: ["не работает на щебне/гравии"],
      cases: ["3PL-склад, Москва, 2025"],
    },
    dataQuality: {
      source: "demo-assumption",
      lastUpdated: "2026-09",
      confidence: "средняя",
    },
  },
  {
    id: "vac-pro",
    identification: {
      vendor: "CleanBot",
      name: "CleanBot Pro 1200",
      type: "vacuum",
      purpose: "Автономная уборка складских полов, высокая производительность",
      country: "РФ",
      availability: "в наличии",
    },
    technical: {
      throughput: 3200,
      throughputUnit: "м²/ч",
      speed: 1.6,
      autonomyHours: 6,
      energy: { workPowerKw: 0.7, idlePowerKw: 0.03, chargeHours: 2 },
      positioningAccuracyMm: 30,
      navigationType: "LIDAR + SLAM",
    },
    infra: {
      floorRequirement: "ровный пол, уклон < 3%",
      chargingStations: 2,
    },
    economics: {
      equipmentCost: 1650000,
      infrastructureCost: 140000,
      softwareCost: 60000,
      implementationCost: 90000,
      commissioningCost: 30000,
      trainingCost: 15000,
      maintenanceCostPerYear: 120000,
      serviceCostPerYear: 70000,
      lifespanYears: 6,
      raas: { monthlyRate: 68000, contractMonths: 24, buyoutOption: true },
    },
    applicability: {
      objectTypes: ["warehouse"],
      processes: ["floor_cleaning"],
      limitations: [],
      cases: ["Дарксторы, Санкт-Петербург, 2025"],
    },
    dataQuality: {
      source: "demo-assumption",
      lastUpdated: "2026-09",
      confidence: "средняя",
    },
  },
  {
    id: "arm-sorter",
    identification: {
      vendor: "ArmTech",
      name: "ArmTech Sorter S1",
      type: "arm",
      purpose: "Сортировка и перегрузка штучных грузов между лентами",
      country: "РФ",
      availability: "в наличии",
    },
    technical: {
      throughput: 900,
      throughputUnit: "оп/ч",
      speed: null,
      autonomyHours: null,
      energy: { workPowerKw: 3, idlePowerKw: 0.3, chargeHours: null },
      positioningAccuracyMm: 5,
      navigationType: "фиксированная база",
    },
    infra: {
      floorRequirement: "конвейерные линии по обе стороны",
      power: "380В, 3кВт",
      conveyorRequired: true,
      conveyorPerRobotM: 15,
    },
    economics: {
      equipmentCost: 2800000,
      infrastructureCost: 250000,
      softwareCost: 120000,
      implementationCost: 250000,
      commissioningCost: 60000,
      trainingCost: 30000,
      maintenanceCostPerYear: 180000,
      serviceCostPerYear: 90000,
      lifespanYears: 7,
      raas: { monthlyRate: 95000, contractMonths: 36, buyoutOption: true },
    },
    applicability: {
      objectTypes: ["warehouse"],
      processes: ["sorting"],
      limitations: ["грузы до 15 кг", "габариты до 60×40×40 см"],
      cases: ["Сортировочный хаб маркетплейса, 2024"],
    },
    dataQuality: {
      source: "demo-assumption",
      lastUpdated: "2026-09",
      confidence: "средняя",
    },
  },
  {
    id: "arm-heavy",
    identification: {
      vendor: "ArmTech",
      name: "ArmTech Sorter S2 Heavy",
      type: "arm",
      purpose: "Сортировка тяжёлых и крупногабаритных грузов",
      country: "РФ",
      availability: "под заказ",
    },
    technical: {
      throughput: 600,
      throughputUnit: "оп/ч",
      speed: null,
      autonomyHours: null,
      energy: { workPowerKw: 5, idlePowerKw: 0.4, chargeHours: null },
      positioningAccuracyMm: 8,
      navigationType: "фиксированная база",
    },
    infra: {
      floorRequirement: "усиленный фундамент под основание",
      power: "380В, 5кВт",
      conveyorRequired: true,
      conveyorPerRobotM: 18,
    },
    economics: {
      equipmentCost: 4100000,
      infrastructureCost: 380000,
      softwareCost: 150000,
      implementationCost: 320000,
      commissioningCost: 90000,
      trainingCost: 40000,
      maintenanceCostPerYear: 240000,
      serviceCostPerYear: 130000,
      lifespanYears: 8,
      raas: { monthlyRate: 140000, contractMonths: 36, buyoutOption: true },
    },
    applicability: {
      objectTypes: ["warehouse"],
      processes: ["sorting"],
      limitations: ["грузы до 40 кг"],
      cases: [],
    },
    dataQuality: {
      source: "demo-assumption",
      lastUpdated: "2026-09",
      confidence: "низкая — нет подтверждённого кейса",
    },
  },
  {
    id: "loader-100",
    identification: {
      vendor: "ForkBot",
      name: "ForkBot L100",
      type: "loader",
      purpose: "Автономный погрузчик: приём груза у ворот и складирование",
      country: "РФ",
      availability: "в наличии",
    },
    technical: {
      throughput: 90,
      throughputUnit: "ед./ч",
      capacityKg: 100,
      speed: 2.0,
      autonomyHours: 8,
      energy: { workPowerKw: 0.9, idlePowerKw: 0.05, chargeHours: 2 },
      positioningAccuracyMm: 20,
      navigationType: "LIDAR + SLAM",
    },
    infra: {
      floorRequirement: "ровный пол, проезд шире 3,5 м",
      chargingStations: 1,
    },
    economics: {
      equipmentCost: 1900000,
      infrastructureCost: 150000,
      softwareCost: 80000,
      implementationCost: 120000,
      commissioningCost: 40000,
      trainingCost: 20000,
      maintenanceCostPerYear: 140000,
      serviceCostPerYear: 75000,
      lifespanYears: 7,
      raas: { monthlyRate: 72000, contractMonths: 24, buyoutOption: true },
    },
    applicability: {
      objectTypes: ["warehouse"],
      processes: ["loading"],
      limitations: ["грузоподъёмность до 100 кг"],
      cases: [],
    },
    dataQuality: {
      source: "demo-assumption",
      lastUpdated: "2026-09",
      confidence: "низкая — нет подтверждённого кейса",
    },
  },
  {
    id: "loader-100-plus",
    identification: {
      vendor: "ForkBot",
      name: "ForkBot L100 Plus",
      type: "loader",
      purpose: "Погрузчик с повышенной скоростью цикла",
      country: "РФ",
      availability: "под заказ",
    },
    technical: {
      throughput: 140,
      throughputUnit: "ед./ч",
      capacityKg: 100,
      speed: 2.4,
      autonomyHours: 10,
      energy: { workPowerKw: 1.3, idlePowerKw: 0.06, chargeHours: 2.5 },
      positioningAccuracyMm: 15,
      navigationType: "LIDAR + SLAM",
    },
    infra: {
      floorRequirement: "ровный пол, проезд шире 3,5 м",
      chargingStations: 1,
    },
    economics: {
      equipmentCost: 2600000,
      infrastructureCost: 200000,
      softwareCost: 100000,
      implementationCost: 150000,
      commissioningCost: 50000,
      trainingCost: 25000,
      maintenanceCostPerYear: 190000,
      serviceCostPerYear: 100000,
      lifespanYears: 8,
      raas: { monthlyRate: 98000, contractMonths: 24, buyoutOption: true },
    },
    applicability: {
      objectTypes: ["warehouse"],
      processes: ["loading"],
      limitations: ["грузоподъёмность до 100 кг"],
      cases: [],
    },
    dataQuality: {
      source: "demo-assumption",
      lastUpdated: "2026-09",
      confidence: "низкая — нет подтверждённого кейса",
    },
  },
  {
    id: "transporter-t1",
    identification: {
      vendor: "LowCart",
      name: "LowCart T1",
      type: "transporter",
      purpose: "Транспортировка грузов: груз на неё ставит погрузчик или манипулятор, сама только возит",
      country: "РФ",
      availability: "в наличии",
    },
    technical: {
      throughput: 75,
      throughputUnit: "ед./ч",
      capacityKg: 150,
      speed: 1.8,
      autonomyHours: 9,
      energy: { workPowerKw: 0.5, idlePowerKw: 0.03, chargeHours: 1.5 },
      positioningAccuracyMm: 15,
      navigationType: "LIDAR + SLAM",
    },
    infra: {
      floorRequirement: "ровный пол; груз ставится погрузчиком/манипулятором, своих вил нет",
      chargingStations: 1,
    },
    economics: {
      equipmentCost: 1300000,
      infrastructureCost: 90000,
      softwareCost: 60000,
      implementationCost: 90000,
      commissioningCost: 25000,
      trainingCost: 12000,
      maintenanceCostPerYear: 95000,
      serviceCostPerYear: 55000,
      lifespanYears: 6,
      raas: { monthlyRate: 48000, contractMonths: 24, buyoutOption: true },
    },
    applicability: {
      objectTypes: ["warehouse", "airport"],
      processes: ["loading", "transport"],
      limitations: ["грузоподъёмность до 150 кг", "своих вил/захвата нет — загрузка сторонним оборудованием"],
      cases: [],
    },
    dataQuality: {
      source: "demo-assumption",
      lastUpdated: "2026-09",
      confidence: "низкая — нет подтверждённого кейса",
    },
  },
  {
    id: "transporter-t2-heavy",
    identification: {
      vendor: "LowCart",
      name: "LowCart T2 Heavy",
      type: "transporter",
      purpose: "Транспортировка грузов повышенной массы",
      country: "РФ",
      availability: "под заказ",
    },
    technical: {
      throughput: 55,
      throughputUnit: "ед./ч",
      capacityKg: 300,
      speed: 1.4,
      autonomyHours: 8,
      energy: { workPowerKw: 0.8, idlePowerKw: 0.05, chargeHours: 2 },
      positioningAccuracyMm: 15,
      navigationType: "LIDAR + SLAM",
    },
    infra: {
      floorRequirement: "ровный пол; груз ставится погрузчиком/манипулятором",
      chargingStations: 1,
    },
    economics: {
      equipmentCost: 1850000,
      infrastructureCost: 130000,
      softwareCost: 75000,
      implementationCost: 120000,
      commissioningCost: 35000,
      trainingCost: 16000,
      maintenanceCostPerYear: 130000,
      serviceCostPerYear: 75000,
      lifespanYears: 7,
      raas: { monthlyRate: 66000, contractMonths: 24, buyoutOption: true },
    },
    applicability: {
      objectTypes: ["warehouse", "airport"],
      processes: ["loading", "transport"],
      limitations: ["грузоподъёмность до 300 кг", "своих вил/захвата нет"],
      cases: [],
    },
    dataQuality: {
      source: "demo-assumption",
      lastUpdated: "2026-09",
      confidence: "низкая — нет подтверждённого кейса",
    },
  },
  {
    id: "floor-washer-1",
    identification: {
      vendor: "Мойдодыр",
      name: "Мойдодыр W1",
      type: "washer",
      purpose: "Влажная мойка полов щёткой (не сухая уборка пылесосом)",
      country: "РФ",
      availability: "в наличии",
    },
    technical: {
      throughput: 2200,
      throughputUnit: "м²/ч",
      speed: 1.2,
      autonomyHours: 3.5,
      energy: { workPowerKw: 0.6, idlePowerKw: 0.03, chargeHours: 2 },
      positioningAccuracyMm: 40,
      navigationType: "LIDAR + SLAM",
    },
    infra: {
      floorRequirement: "ровный пол, уклон < 2%, слив/заправка водой",
      chargingStations: 1,
    },
    economics: {
      equipmentCost: 1150000,
      infrastructureCost: 110000,
      softwareCost: 45000,
      implementationCost: 70000,
      commissioningCost: 25000,
      trainingCost: 12000,
      maintenanceCostPerYear: 100000,
      serviceCostPerYear: 55000,
      lifespanYears: 5,
      raas: { monthlyRate: 50000, contractMonths: 24, buyoutOption: true },
    },
    applicability: {
      objectTypes: ["warehouse"],
      processes: ["floor_cleaning"],
      limitations: ["нужна вода/слив — не подходит без соответствующей инфраструктуры"],
      cases: [],
    },
    dataQuality: {
      source: "demo-assumption",
      lastUpdated: "2026-09",
      confidence: "низкая — нет подтверждённого кейса",
    },
  },
  {
    id: "weld-arm-1",
    identification: {
      vendor: "Ручка",
      name: "Ручка WA-1",
      type: "weldarm",
      purpose: "Манипулятор-клешня: сварка металла, подъём коробок — альтернатива конвейерной роборуке",
      country: "РФ",
      availability: "под заказ",
    },
    technical: {
      throughput: 750,
      throughputUnit: "оп/ч",
      speed: null,
      autonomyHours: null,
      energy: { workPowerKw: 3.6, idlePowerKw: 0.35, chargeHours: null },
      positioningAccuracyMm: 4,
      navigationType: "фиксированная база",
    },
    infra: {
      floorRequirement: "конвейерные линии по обе стороны",
      power: "380В, 3.6кВт",
      conveyorRequired: true,
      conveyorPerRobotM: 15,
    },
    economics: {
      equipmentCost: 3100000,
      infrastructureCost: 270000,
      softwareCost: 130000,
      implementationCost: 260000,
      commissioningCost: 65000,
      trainingCost: 35000,
      maintenanceCostPerYear: 190000,
      serviceCostPerYear: 95000,
      lifespanYears: 7,
      raas: { monthlyRate: 100000, contractMonths: 36, buyoutOption: true },
    },
    applicability: {
      objectTypes: ["warehouse"],
      processes: ["sorting"],
      limitations: ["грузы до 20 кг", "клешня — не для хрупких грузов без доп. оснастки"],
      cases: [],
    },
    dataQuality: {
      source: "demo-assumption",
      lastUpdated: "2026-09",
      confidence: "низкая — нет подтверждённого кейса",
    },
  },
  {
    id: "storage-cube-1",
    identification: {
      vendor: "СтойкаБокс",
      name: "СтойкаБокс SB-400",
      type: "storagecube",
      purpose: "Роботизированная кубическая система хранения — стационарная башня с шаттлом/лифтом внутри, не ездит по складу",
      country: "РФ",
      availability: "под заказ",
    },
    technical: {
      throughput: 90,
      throughputUnit: "ед./ч",
      speed: null,
      autonomyHours: null,
      energy: { workPowerKw: 1.4, idlePowerKw: 0.15, chargeHours: null },
      positioningAccuracyMm: 5,
      navigationType: "фиксированная база (шаттл внутри башни)",
    },
    infra: {
      floorRequirement: "усиленный фундамент, подача груза манипулятором/конвейером или напрямую погрузчиком",
      power: "380В, 1.4кВт",
    },
    economics: {
      equipmentCost: 4600000,
      infrastructureCost: 520000,
      softwareCost: 180000,
      implementationCost: 380000,
      commissioningCost: 120000,
      trainingCost: 30000,
      maintenanceCostPerYear: 230000,
      serviceCostPerYear: 110000,
      lifespanYears: 10,
      raas: { monthlyRate: 165000, contractMonths: 48, buyoutOption: false },
    },
    applicability: {
      objectTypes: ["warehouse"],
      processes: ["loading"],
      limitations: ["не ездит — фиксированное место установки", "нужен фундамент под вес башни"],
      cases: [],
    },
    dataQuality: {
      source: "demo-assumption",
      lastUpdated: "2026-09",
      confidence: "низкая — нет подтверждённого кейса",
    },
  },
];

export function catalogFor(objectTypeId, processId) {
  return CATALOG.filter(
    (item) =>
      item.applicability.objectTypes.includes(objectTypeId) &&
      (!processId || item.applicability.processes.includes(processId))
  );
}

export function getCatalogItem(id) {
  return CATALOG.find((item) => item.id === id) ?? null;
}
