// Реестр типов объектов (ТЗ 3.2.1). Склад — рабочий, с полной схемой параметров.
// Аэропорт и мед.учреждение — заглушки, показывают расширяемость архитектуры
// (ТЗ 4.2.6): добавление нового типа объекта не требует переработки ядра
// (economics.js / catalog.js / useEconomicsState.js), только новую схему + адаптер.

export const OBJECT_TYPES = {
  warehouse: {
    id: "warehouse",
    label: "Склад",
    icon: "📦",
    comingSoon: false,
    processes: [
      { id: "floor_cleaning", label: "Уборка пола" },
      { id: "sorting", label: "Сортировка/перегрузка" },
      { id: "loading", label: "Погрузка и складирование" },
    ],
    // Параметры разделены по группам из ТЗ (входные данные по складу): площадь и
    // рабочие зоны, режим работы, объём операций, хранение и груз, персонал и
    // текущий процесс, маршруты, ограничения планировки. Этажи из параметров
    // склада убраны: система этажей (floorLevel.js) осталась в симуляции для
    // медучреждений.
    paramSchema: [
      {
        key: "floorAreaM2",
        group: "Площадь, рабочие зоны и планировка",
        label: "Площадь склада",
        unit: "м²",
        type: "number",
        min: 500,
        max: 40000,
        step: 500,
        default: 10000,
        hint: "От площади зависит число чанков пола и то, как быстро роботы пересекают склад",
      },
      {
        key: "workZonePct",
        group: "Площадь, рабочие зоны и планировка",
        label: "Рабочая зона роботов",
        unit: "% площади",
        type: "number",
        min: 40,
        max: 100,
        step: 5,
        default: 85,
        hint: "Доля площади, доступная роботам; остальное — зона разгрузки у ворот, куда пылесосы и роборуки не заходят. Влияет на площадь уборки и число роборук",
      },
      {
        key: "layoutRestriction",
        group: "Площадь, рабочие зоны и планировка",
        label: "Ограничения планировки",
        type: "select",
        default: "none",
        options: [
          { value: "none", label: "Ограничений нет", speedFactor: 1 },
          { value: "columns", label: "Колонны и стеллажи (−8% к скорости)", speedFactor: 0.92 },
          { value: "narrow", label: "Узкие проходы (−20% к скорости)", speedFactor: 0.8 },
        ],
        hint: "Тесная планировка замедляет роботов: манёвры, объезды, уступание дороги",
      },
      {
        key: "shiftHoursPerDay",
        group: "Режим работы",
        label: "Часов в смену",
        unit: "ч",
        type: "number",
        min: 1,
        max: 12,
        step: 1,
        default: 8,
        hint: "Продолжительность рабочей смены на объекте",
      },
      {
        key: "shiftsPerDay",
        group: "Режим работы",
        label: "Смен в сутки",
        unit: "смен",
        type: "number",
        min: 1,
        max: 3,
        step: 1,
        default: 1,
        hint: "Сколько смен работает склад; от этого зависит годовой объём работы, персонала и электроэнергии",
      },
      {
        key: "daysPerYear",
        group: "Режим работы",
        label: "Рабочих дней в году",
        unit: "дн",
        type: "number",
        min: 1,
        max: 366,
        step: 1,
        default: 305,
        hint: "Например, 365 минус выходные и простои",
      },
      {
        key: "requiredLoadThroughput",
        group: "Объём операций",
        label: "Входящие операции (приёмка)",
        unit: "ед./ч",
        type: "number",
        min: 0,
        max: 1000,
        step: 10,
        default: 360,
        hint: "Грузовых единиц в час, которые приходят с фурами: от этого зависит, как часто приезжают фуры",
      },
      {
        key: "requiredOutboundThroughput",
        group: "Объём операций",
        label: "Исходящие операции (отгрузка)",
        unit: "ед./ч",
        type: "number",
        min: 0,
        max: 1000,
        step: 10,
        default: 360,
        hint: "Грузовых единиц в час, которые нужно подать к воротам и отгрузить в фуры",
      },
      {
        key: "requiredSortThroughput",
        group: "Объём операций",
        label: "Внутрискладские операции",
        unit: "оп/ч",
        type: "number",
        min: 0,
        max: 5000,
        step: 50,
        default: 900,
        hint: "Сортировка и перегрузка внутри склада — пиковая потребность в операциях роборук (табл. 3.5.2)",
      },
      {
        key: "storageType",
        group: "Хранение и грузовая единица",
        label: "Тип хранения",
        type: "select",
        default: "block",
        options: [
          { value: "deep", label: "Глубокие блоки (3 ячейки в глубину)", slotsPerLane: 3 },
          { value: "block", label: "Блоки средней глубины (2 ячейки)", slotsPerLane: 2 },
          { value: "front", label: "Фронтальное (1 ячейка, прямой доступ)", slotsPerLane: 1 },
        ],
        hint: "Определяет глубину полос хранения, а значит вместимость склада и длительность цикла погрузки",
      },
      {
        key: "skuCount",
        group: "Хранение и грузовая единица",
        label: "Количество SKU",
        unit: "SKU",
        type: "number",
        min: 1,
        max: 500,
        step: 1,
        default: 40,
        hint: "Разных товарных позиций на складе; в симуляции грузы окрашены по SKU (различаются первые 8 цветов)",
      },
      {
        key: "cargoWeightKg",
        group: "Хранение и грузовая единица",
        label: "Средняя масса грузовой единицы",
        unit: "кг",
        type: "number",
        min: 10,
        max: 100,
        step: 5,
        default: 50,
        hint: "Чем тяжелее единица относительно грузоподъёмности погрузчика, тем медленнее он едет и тем больше потребляет",
      },
      {
        key: "cargoLengthCm",
        group: "Хранение и грузовая единица",
        label: "Длина грузовой единицы",
        unit: "см",
        type: "number",
        min: 40,
        max: 160,
        step: 10,
        default: 120,
        hint: "Габариты единицы: определяют её размер на поддоне в симуляции",
      },
      {
        key: "cargoWidthCm",
        group: "Хранение и грузовая единица",
        label: "Ширина грузовой единицы",
        unit: "см",
        type: "number",
        min: 40,
        max: 120,
        step: 10,
        default: 80,
        hint: "Габариты единицы",
      },
      {
        key: "cargoHeightCm",
        group: "Хранение и грузовая единица",
        label: "Высота грузовой единицы",
        unit: "см",
        type: "number",
        min: 30,
        max: 150,
        step: 10,
        default: 100,
        hint: "Габариты единицы: от высоты зависит, насколько поднимаются вилы при укладке в два слоя",
      },
      {
        key: "truckPayloadUnits",
        group: "Хранение и грузовая единица",
        label: "Груза в одной фуре",
        unit: "ед.",
        type: "number",
        min: 2,
        max: 18,
        step: 1,
        default: 12,
        hint: "Фура выгружает весь груз разом; при заданном входящем потоке это определяет, как часто приезжают фуры",
      },
      {
        key: "staffCount",
        group: "Персонал и текущий процесс",
        label: "Численность персонала",
        unit: "чел",
        type: "number",
        min: 0,
        max: 100,
        step: 1,
        default: 6,
        hint: "Сколько человек сейчас выполняют процесс вручную",
      },
      {
        key: "hourlyWage",
        group: "Персонал и текущий процесс",
        label: "Стоимость часа персонала",
        unit: "₽/ч",
        type: "number",
        min: 0,
        max: 2000,
        step: 10,
        default: 450,
        hint: "С учётом налогов и страховых взносов",
      },
      {
        key: "manualProductivity",
        group: "Персонал и текущий процесс",
        label: "Производительность текущего процесса",
        unit: "оп/чел·ч",
        type: "number",
        min: 5,
        max: 300,
        step: 5,
        default: 45,
        hint: "Сколько операций (единиц груза) один сотрудник выполняет за час сейчас — с ней сравнивается потребность склада",
      },
      {
        key: "routeLengthM",
        group: "Маршруты",
        label: "Средняя протяжённость маршрута",
        unit: "м",
        type: "number",
        min: 10,
        max: 200,
        step: 5,
        default: 60,
        hint: "Путь груза от ворот до места хранения: от него зависит длительность цикла погрузчика и то, куда в симуляции развозят груз",
      },
      {
        key: "electricityTariff",
        group: "Экономика",
        label: "Тариф на электроэнергию",
        unit: "₽/кВт·ч",
        type: "number",
        min: 1,
        max: 30,
        step: 0.5,
        default: 7.5,
        hint: "Стоимость электроэнергии для зарядки и питания роботов",
      },
      {
        key: "loadFactor",
        group: "Экономика",
        label: "Коэффициент загрузки оборудования",
        unit: "доля",
        type: "number",
        min: 0.1,
        max: 1,
        step: 0.05,
        default: 0.85,
        hint: "Доля времени, когда робот реально работает",
      },
      {
        key: "horizonYears",
        group: "Экономика",
        label: "Горизонт расчёта TCO",
        unit: "лет",
        type: "number",
        min: 1,
        max: 15,
        step: 1,
        default: 5,
        hint: "ТЗ требует не менее 5 лет",
      },
    ],
  },

  airport: {
    id: "airport",
    label: "Аэропорт",
    icon: "✈️",
    comingSoon: true,
    processes: [{ id: "baggage", label: "Перемещение багажа" }],
    paramSchema: [
      {
        key: "peakPassengerFlow",
        label: "Пиковый пассажиропоток",
        unit: "пасс/ч",
        type: "number",
        min: 0,
        max: 20000,
        default: 1200,
        hint: "Заполняется при реализации сценария «Аэропорт»",
      },
    ],
  },

  medical: {
    id: "medical",
    label: "Медицинское учреждение",
    icon: "🏥",
    comingSoon: true,
    processes: [{ id: "logistics", label: "Логистика грузов/белья/медикаментов" }],
    paramSchema: [
      {
        key: "transportRunsPerDay",
        label: "Перевозок в сутки",
        unit: "рейсов",
        type: "number",
        min: 0,
        max: 2000,
        default: 80,
        hint: "Заполняется при реализации сценария «Медучреждение»",
      },
    ],
  },
};

export const OBJECT_TYPE_LIST = Object.values(OBJECT_TYPES);

export function getObjectType(id) {
  return OBJECT_TYPES[id] ?? null;
}

// Выбранный вариант поля-списка (select) с его числовыми свойствами (speedFactor, slotsPerLane...).
export function selectOption(objectTypeId, key, value) {
  const field = getObjectType(objectTypeId)?.paramSchema.find((f) => f.key === key);
  return field?.options?.find((o) => o.value === value) ?? field?.options?.[0] ?? null;
}

export function defaultParamsFor(objectTypeId) {
  const type = getObjectType(objectTypeId);
  if (!type) return {};

  return Object.fromEntries(
    type.paramSchema.map((field) => [field.key, field.default])
  );
}
