// Реестр типов объектов (ТЗ 3.2.1). Склад — рабочий, с полной схемой параметров.
// Аэропорт и мед.учреждение — заглушки, показывают расширяемость архитектуры
// (ТЗ 4.2.6): добавление нового типа объекта не требует переработки ядра
// (economics.js / catalog.js / useEconomicsState.js), только новую схему + адаптер.

export const OBJECT_TYPES = {
  warehouse: {
    id: "warehouse",
    label: "Склад",
    icon: "📦",
    comingSoon: false,
    processes: [
      { id: "floor_cleaning", label: "Уборка пола" },
      { id: "sorting", label: "Сортировка/перегрузка" },
      { id: "loading", label: "Погрузка и складирование" },
    ],
    // Параметры разделены по группам из ТЗ (входные данные по складу): площадь и
    // рабочие зоны, режим работы, объём операций, хранение и груз, персонал и
    // текущий процесс, маршруты, ограничения планировки. Этажи из параметров
    // склада убраны: система этажей (floorLevel.js) осталась в симуляции для
    // медучреждений.
    paramSchema: [
      {
        key: "floorAreaM2",
        group: "Площадь, рабочие зоны и планировка",
        label: "Площадь склада",
        unit: "м²",
        type: "number",
        min: 1000,
        max: 100000,
        step: 500,
        default: 10000,
        hint: "От площади зависит число чанков пола и то, как быстро роботы пересекают склад",
      },
      {
        key: "workZonePct",
        group: "Площадь, рабочие зоны и планировка",
        label: "Рабочая зона роботов",
        unit: "% площади",
        type: "number",
        min: 40,
        max: 100,
        step: 5,
        default: 85,
        hint: "Доля площади, доступная роботам; остальное — зона разгрузки у ворот, куда пылесосы и роборуки не заходят. Влияет на площадь уборки и число роборук",
      },
      {
        key: "layoutRestriction",
        group: "Площадь, рабочие зоны и планировка",
        label: "Ограничения планировки",
        type: "select",
        default: "none",
        options: [
          { value: "none", label: "Ограничений нет", speedFactor: 1 },
          { value: "columns", label: "Колонны и стеллажи (−8% к скорости)", speedFactor: 0.92 },
          { value: "narrow", label: "Узкие проходы (−20% к скорости)", speedFactor: 0.8 },
        ],
        hint: "Тесная планировка замедляет роботов: манёвры, объезды, уступание дороги",
      },
      {
        key: "shiftHoursPerDay",
        group: "Режим работы",
        label: "Часов в смену",
        unit: "ч",
        type: "number",
        min: 1,
        max: 12,
        step: 1,
        default: 8,
        hint: "Продолжительность рабочей смены на объекте",
      },
      {
        key: "shiftsPerDay",
        group: "Режим работы",
        label: "Смен в сутки",
        unit: "смен",
        type: "number",
        min: 1,
        max: 3,
        step: 1,
        default: 1,
        hint: "Сколько смен работает склад; от этого зависит годовой объём работы, персонала и электроэнергии",
      },
      {
        key: "daysPerYear",
        group: "Режим работы",
        label: "Рабочих дней в году",
        unit: "дн",
        type: "number",
        min: 1,
        max: 366,
        step: 1,
        default: 305,
        hint: "Например, 365 минус выходные и простои",
      },
      {
        key: "requiredLoadThroughput",
        group: "Объём операций",
        label: "Входящие операции (приёмка)",
        unit: "ед./ч",
        type: "number",
        min: 0,
        max: 1000,
        step: 10,
        default: 360,
        hint: "Среднечасовой поток с фурами: от этого зависит, как часто они приезжают, и (с поправкой на пиковый коэффициент ниже) — требуемое число погрузчиков",
      },
      {
        key: "requiredOutboundThroughput",
        group: "Объём операций",
        label: "Исходящие операции (отгрузка)",
        unit: "ед./ч",
        type: "number",
        min: 0,
        max: 1000,
        step: 10,
        default: 360,
        hint: "Среднечасовой поток, который нужно подать к воротам и отгрузить в фуры",
      },
      {
        key: "requiredSortThroughput",
        group: "Объём операций",
        label: "Внутрискладские операции",
        unit: "оп/ч",
        type: "number",
        min: 0,
        max: 5000,
        step: 50,
        default: 900,
        hint: "Сортировка и перегрузка внутри склада — среднечасовой поток (табл. 3.5.2)",
      },
      {
        key: "peakLoadFactor",
        group: "Объём операций",
        label: "Пиковый коэффициент нагрузки",
        unit: "×",
        type: "number",
        min: 1,
        max: 2.5,
        step: 0.1,
        default: 1.5,
        hint: "Отношение максимальной часовой нагрузки к среднечасовой (для e-commerce — до 2.5). Переводит средние потоки выше в пиковую потребность для расчёта числа роборук и погрузчиков (ТЗ 3.5.2)",
      },
      {
        key: "storageType",
        group: "Хранение и грузовая единица",
        label: "Тип хранения",
        type: "select",
        default: "block",
        options: [
          { value: "deep", label: "Глубокие блоки (3 ячейки в глубину)", slotsPerLane: 3 },
          { value: "block", label: "Блоки средней глубины (2 ячейки)", slotsPerLane: 2 },
          { value: "front", label: "Фронтальное (1 ячейка, прямой доступ)", slotsPerLane: 1 },
        ],
        hint: "Определяет глубину полос хранения, а значит вместимость склада и длительность цикла погрузки",
      },
      {
        key: "skuCount",
        group: "Хранение и грузовая единица",
        label: "Количество SKU",
        unit: "SKU",
        type: "number",
        min: 1,
        max: 10000,
        step: 10,
        default: 40,
        hint: "Разных товарных позиций на складе; в симуляции грузы окрашены по SKU (различаются первые 8 цветов)",
      },
      {
        key: "cargoWeightKg",
        group: "Хранение и грузовая единица",
        label: "Средняя масса грузовой единицы",
        unit: "кг",
        type: "number",
        min: 1,
        max: 150,
        step: 5,
        default: 50,
        hint: "Чем тяжелее единица относительно грузоподъёмности погрузчика, тем медленнее он едет и тем больше потребляет. Тяжелее демо-каталога погрузчиков (до 100 кг) — решения станут крайне медленными или неприменимыми",
      },
      {
        key: "cargoLengthCm",
        group: "Хранение и грузовая единица",
        label: "Длина грузовой единицы",
        unit: "см",
        type: "number",
        min: 40,
        max: 160,
        step: 10,
        default: 120,
        hint: "Габариты единицы: определяют её размер на поддоне в симуляции",
      },
      {
        key: "cargoWidthCm",
        group: "Хранение и грузовая единица",
        label: "Ширина грузовой единицы",
        unit: "см",
        type: "number",
        min: 40,
        max: 120,
        step: 10,
        default: 80,
        hint: "Габариты единицы",
      },
      {
        key: "cargoHeightCm",
        group: "Хранение и грузовая единица",
        label: "Высота грузовой единицы",
        unit: "см",
        type: "number",
        min: 30,
        max: 150,
        step: 10,
        default: 100,
        hint: "Габариты единицы: от высоты зависит, насколько поднимаются вилы при укладке в два слоя",
      },
      {
        key: "truckPayloadUnits",
        group: "Хранение и грузовая единица",
        label: "Груза в одной фуре",
        unit: "ед.",
        type: "number",
        min: 2,
        max: 18,
        step: 1,
        default: 12,
        hint: "Фура выгружает весь груз разом; при заданном входящем потоке это определяет, как часто приезжают фуры",
      },
      {
        key: "staffCount",
        group: "Персонал и текущий процесс",
        label: "Численность персонала",
        unit: "чел",
        type: "number",
        min: 0,
        max: 100,
        step: 1,
        default: 6,
        hint: "Сколько человек сейчас выполняют процесс вручную",
      },
      {
        key: "hourlyWage",
        group: "Персонал и текущий процесс",
        label: "Стоимость часа персонала",
        unit: "₽/ч",
        type: "number",
        min: 0,
        max: 2000,
        step: 10,
        default: 450,
        hint: "С учётом налогов и страховых взносов",
      },
      {
        key: "manualProductivity",
        group: "Персонал и текущий процесс",
        label: "Производительность текущего процесса",
        unit: "оп/чел·ч",
        type: "number",
        min: 5,
        max: 300,
        step: 5,
        default: 45,
        hint: "Сколько операций (единиц груза) один сотрудник выполняет за час сейчас — с ней сравнивается потребность склада",
      },
      {
        key: "routeLengthM",
        group: "Маршруты",
        label: "Средняя протяжённость маршрута",
        unit: "м",
        type: "number",
        min: 10,
        max: 200,
        step: 5,
        default: 60,
        hint: "Путь груза от ворот до места хранения: от него зависит длительность цикла погрузчика и то, куда в симуляции развозят груз",
      },
      {
        key: "electricityTariff",
        group: "Экономика",
        label: "Тариф на электроэнергию",
        unit: "₽/кВт·ч",
        type: "number",
        min: 1,
        max: 30,
        step: 0.5,
        default: 7.5,
        hint: "Стоимость электроэнергии для зарядки и питания роботов",
      },
      {
        key: "loadFactor",
        group: "Экономика",
        label: "Коэффициент загрузки оборудования",
        unit: "доля",
        type: "number",
        min: 0.1,
        max: 1,
        step: 0.05,
        default: 0.85,
        hint: "Доля времени, когда робот реально работает",
      },
      {
        key: "budgetCapexMRub",
        group: "Экономика",
        label: "Планируемый бюджет на роботизацию (CAPEX)",
        unit: "млн ₽",
        type: "number",
        min: 10,
        max: 500,
        step: 5,
        default: 80,
        hint: "Ориентир для проверки применимости решений (ТЗ 3.4.1) — платформа предупредит, если расчётный CAPEX сценария выше",
      },
      {
        key: "horizonYears",
        group: "Экономика",
        label: "Горизонт расчёта TCO",
        unit: "лет",
        type: "number",
        min: 1,
        max: 15,
        step: 1,
        default: 5,
        hint: "ТЗ требует не менее 5 лет",
      },
    ],
  },

  // Схема — по минимальному составу параметров ТЗ 3.2.1 и демо-датасету организатора
  // («Датасеты_хакатон», лист «Аэропорт»); значения default/min/max взяты оттуда же
  // (базовое значение и диапазон). comingSoon остаётся true, пока нет airportAdapter.js
  // и симуляции — это только основа схемы, чтобы позже не переделывать ядро (ТЗ 4.2.6).
  airport: {
    id: "airport",
    label: "Аэропорт",
    icon: "✈️",
    comingSoon: true,
    processes: [
      { id: "baggage", label: "Багаж и сортировка" },
      { id: "ramp", label: "Наземное обслуживание (перрон)" },
      { id: "cleaning", label: "Уборка терминала" },
    ],
    paramSchema: [
      {
        key: "terminalAreaM2",
        group: "Терминал и пассажиропоток",
        label: "Площадь терминала(ов)",
        unit: "м²",
        type: "number",
        min: 8000,
        max: 500000,
        step: 1000,
        default: 85000,
        hint: "База для расчёта маршрутов роботов-транспортировщиков",
      },
      {
        key: "apronAreaM2",
        group: "Терминал и пассажиропоток",
        label: "Площадь перрона и технических зон",
        unit: "м²",
        type: "number",
        min: 10000,
        max: 800000,
        step: 5000,
        default: 100000,
        hint: "Открытая зона — ограничения на перемещение роботов (погода, допуски airside)",
      },
      {
        key: "gatesCount",
        group: "Терминал и пассажиропоток",
        label: "Количество выходов на посадку",
        unit: "шт.",
        type: "number",
        min: 8,
        max: 50,
        step: 1,
        default: 20,
        hint: "Влияет на маршруты доставки и количество роботов",
      },
      {
        key: "dailyPassengers",
        group: "Терминал и пассажиропоток",
        label: "Среднесуточный пассажиропоток",
        unit: "пасс./сут",
        type: "number",
        min: 1400,
        max: 137000,
        step: 100,
        default: 23300,
        hint: "= годовой поток / 365",
      },
      {
        key: "peakPassengersPerHour",
        group: "Терминал и пассажиропоток",
        label: "Пиковый пассажиропоток (PHF)",
        unit: "пасс./ч",
        type: "number",
        min: 200,
        max: 18000,
        step: 50,
        default: 3200,
        hint: "Пиковая потребность для расчёта количества роботов (табл. 3.5.2)",
      },
      {
        key: "dailyFlights",
        group: "Наземное обслуживание и багаж",
        label: "Среднесуточное количество рейсов",
        unit: "рейсов/сут",
        type: "number",
        min: 30,
        max: 1200,
        step: 10,
        default: 280,
        hint: "Взлёт + посадка",
      },
      {
        key: "turnaroundMin",
        group: "Наземное обслуживание и багаж",
        label: "Среднее время оборота ВС (TAT)",
        unit: "мин",
        type: "number",
        min: 25,
        max: 90,
        step: 5,
        default: 45,
        hint: "Посадка → взлёт. Ключевой KPI перрона",
      },
      {
        key: "baggageUnitsPerDay",
        group: "Наземное обслуживание и багаж",
        label: "Объём перемещения багажа",
        unit: "ед./сут",
        type: "number",
        min: 3000,
        max: 300000,
        step: 1000,
        default: 35000,
        hint: "Целевой KPI для багажных AMR и сортировочных систем",
      },
      {
        key: "baggageUnitWeightKg",
        group: "Наземное обслуживание и багаж",
        label: "Средняя масса единицы багажа",
        unit: "кг",
        type: "number",
        min: 10,
        max: 35,
        step: 1,
        default: 18,
        hint: "Для расчёта грузоподъёмности багажных роботов",
      },
      {
        key: "cleanedAreaM2",
        group: "Уборка и внутрипортовая логистика",
        label: "Площадь роботизированной уборки",
        unit: "м²",
        type: "number",
        min: 4800,
        max: 300000,
        step: 1000,
        default: 51000,
        hint: "~60–70% площади терминала без режимных и закрытых зон",
      },
      {
        key: "rampStaffCount",
        group: "Персонал",
        label: "Персонал наземного обслуживания (рамп)",
        unit: "чел.",
        type: "number",
        min: 50,
        max: 2000,
        step: 10,
        default: 320,
        hint: "Целевая группа для частичного высвобождения на рутинных операциях",
      },
      {
        key: "rampWageRubMonth",
        group: "Персонал",
        label: "З/п сотрудника рампа (gross)",
        unit: "₽/мес.",
        type: "number",
        min: 70000,
        max: 150000,
        step: 5000,
        default: 100000,
        hint: "До вычета НДФЛ; для ФОТ прибавляется коэффициент начислений",
      },
      {
        key: "payrollTaxFactor",
        group: "Персонал",
        label: "Коэффициент начислений на ФОТ",
        unit: "доля",
        type: "number",
        min: 1.302,
        max: 1.302,
        step: 0.001,
        default: 1.302,
        hint: "Страховые взносы: ОПФ 22% + ОМС 5.1% + ОСС 2.9% + НСиПЗ 0.2%",
      },
      {
        key: "restrictedZonesCount",
        group: "Безопасность и ограничения",
        label: "Количество режимных зон",
        unit: "шт.",
        type: "number",
        min: 2,
        max: 8,
        step: 1,
        default: 4,
        hint: "Airside, landside, стерильная зона, перрон — у каждой свои допуски для роботов",
      },
      {
        key: "chargingPowerKw",
        group: "Безопасность и ограничения",
        label: "Доступная мощность зарядной инфраструктуры",
        unit: "кВт",
        type: "number",
        min: 50,
        max: 2000,
        step: 50,
        default: 300,
        hint: "Ограничивает количество и мощность зарядных станций роботов",
      },
      {
        key: "budgetCapexMRub",
        group: "Экономика",
        label: "Планируемый бюджет на роботизацию (CAPEX)",
        unit: "млн ₽",
        type: "number",
        min: 20,
        max: 800,
        step: 10,
        default: 120,
        hint: "Ориентир для фильтрации решений при подборе (ТЗ 3.4.1)",
      },
      {
        key: "horizonYears",
        group: "Экономика",
        label: "Горизонт расчёта TCO",
        unit: "лет",
        type: "number",
        min: 5,
        max: 15,
        step: 1,
        default: 7,
        hint: "Аэропортовые проекты — длиннее горизонт из-за сложности интеграции",
      },
    ],
  },

  // Схема — по минимальному составу параметров ТЗ 3.2.1 и демо-датасету организатора
  // (лист «Медучреждение»). comingSoon остаётся true до появления medicalAdapter.js и
  // симуляции; здесь только основа схемы (ТЗ 4.2.6).
  medical: {
    id: "medical",
    label: "Медицинское учреждение",
    icon: "🏥",
    comingSoon: true,
    processes: [
      { id: "meals", label: "Доставка питания" },
      { id: "linen", label: "Транспортировка белья" },
      { id: "medication", label: "Доставка медикаментов" },
      { id: "specimens", label: "Доставка анализов/биоматериалов" },
    ],
    paramSchema: [
      {
        key: "buildingAreaM2",
        group: "Общие параметры объекта",
        label: "Общая площадь здания(й)",
        unit: "м²",
        type: "number",
        min: 3000,
        max: 200000,
        step: 1000,
        default: 45000,
        hint: "Влияет на длину маршрутов и количество роботов",
      },
      {
        key: "floorsCount",
        group: "Общие параметры объекта",
        label: "Количество этажей (основной корпус)",
        unit: "шт.",
        type: "number",
        min: 3,
        max: 20,
        step: 1,
        default: 9,
        hint: "5+ этажей — обязательные лифты, ключевой элемент интеграции",
      },
      {
        key: "liftsCount",
        group: "Общие параметры объекта",
        label: "Количество лифтов (грузовых/медицинских)",
        unit: "шт.",
        type: "number",
        min: 1,
        max: 12,
        step: 1,
        default: 4,
        hint: "Пропускная способность лифта — частое узкое место",
      },
      {
        key: "bedsCount",
        group: "Общие параметры объекта",
        label: "Количество коек (стационар)",
        unit: "коек",
        type: "number",
        min: 50,
        max: 2500,
        step: 10,
        default: 650,
        hint: "Основная нагрузка: питание, бельё, медикаменты на койку в сутки",
      },
      {
        key: "bedOccupancyPct",
        group: "Общие параметры объекта",
        label: "Занятость коечного фонда",
        unit: "%",
        type: "number",
        min: 60,
        max: 95,
        step: 1,
        default: 82,
        hint: "Источник: Минздрав РФ, среднее по ЦФО",
      },
      {
        key: "operatingRoomsCount",
        group: "Общие параметры объекта",
        label: "Количество операционных",
        unit: "шт.",
        type: "number",
        min: 2,
        max: 40,
        step: 1,
        default: 12,
        hint: "Доставка стерильных наборов — высокоприоритетный сценарий",
      },
      {
        key: "mealPortionsPerDay",
        group: "Питание",
        label: "Порций питания в сутки",
        unit: "порций/сут",
        type: "number",
        min: 150,
        max: 7500,
        step: 50,
        default: 1950,
        hint: "= коек × занятость × кратность кормления",
      },
      {
        key: "mealDistanceM",
        group: "Питание",
        label: "Расстояние от пищеблока до отделения",
        unit: "м",
        type: "number",
        min: 30,
        max: 500,
        step: 10,
        default: 180,
        hint: "Влияет на длительность маршрута и требуемое число роботов",
      },
      {
        key: "mealDeliveryPointsCount",
        group: "Питание",
        label: "Точек раздачи питания (отделений)",
        unit: "шт.",
        type: "number",
        min: 4,
        max: 60,
        step: 1,
        default: 18,
        hint: "Один рейс робота = одно отделение или несколько в цепочке",
      },
      {
        key: "mealCartWeightKg",
        group: "Питание",
        label: "Масса тележки с питанием (брутто)",
        unit: "кг",
        type: "number",
        min: 40,
        max: 250,
        step: 10,
        default: 120,
        hint: "Определяет требуемую грузоподъёмность робота",
      },
      {
        key: "dirtyLinenKgPerDay",
        group: "Бельё",
        label: "Объём грязного белья",
        unit: "кг/сут",
        type: "number",
        min: 200,
        max: 8000,
        step: 100,
        default: 1800,
        hint: "Норматив ~2.5–3.5 кг на койку в сутки",
      },
      {
        key: "linenDeliveryPointsCount",
        group: "Бельё",
        label: "Точек сбора/выдачи белья",
        unit: "шт.",
        type: "number",
        min: 4,
        max: 60,
        step: 1,
        default: 18,
        hint: "По числу отделений, включая операционный блок",
      },
      {
        key: "medicationRequestsPerDay",
        group: "Медикаменты",
        label: "Заявок на медикаменты в сутки",
        unit: "заявок/сут",
        type: "number",
        min: 40,
        max: 1500,
        step: 10,
        default: 340,
        hint: "1 заявка = 1 отделение, 1 смена; комплектуется в аптеке",
      },
      {
        key: "medicationDeliveryPointsCount",
        group: "Медикаменты",
        label: "Точек доставки (отделения + ОР + реанимация)",
        unit: "шт.",
        type: "number",
        min: 5,
        max: 70,
        step: 1,
        default: 22,
        hint: "Точки назначения маршрута робота",
      },
      {
        key: "statSharePct",
        group: "Медикаменты",
        label: "Доля срочных (STAT) доставок",
        unit: "%",
        type: "number",
        min: 2,
        max: 20,
        step: 1,
        default: 8,
        hint: "STAT — приоритет, робот должен прерывать плановый маршрут",
      },
      {
        key: "specimensPerDay",
        group: "Анализы и биоматериалы",
        label: "Проб биоматериала в сутки",
        unit: "проб/сут",
        type: "number",
        min: 100,
        max: 6000,
        step: 50,
        default: 1200,
        hint: "Забор у пациентов → доставка в КДЛ",
      },
      {
        key: "specimenDeliveryNormMin",
        group: "Анализы и биоматериалы",
        label: "Норматив доставки пробы",
        unit: "мин",
        type: "number",
        min: 10,
        max: 60,
        step: 5,
        default: 30,
        hint: "ГОСТ Р 53079.4-2008; критично для коагулологии и цитологии",
      },
      {
        key: "transportStaffCount",
        group: "Персонал",
        label: "Санитары и транспортировщики",
        unit: "чел.",
        type: "number",
        min: 10,
        max: 300,
        step: 5,
        default: 65,
        hint: "Основная целевая группа для замещения роботами",
      },
      {
        key: "transportStaffWageRubMonth",
        group: "Персонал",
        label: "З/п санитара/транспортировщика (gross)",
        unit: "₽/мес.",
        type: "number",
        min: 38000,
        max: 85000,
        step: 1000,
        default: 55000,
        hint: "Москва/МО, ориентир 2024–2025",
      },
      {
        key: "payrollTaxFactor",
        group: "Персонал",
        label: "Коэффициент начислений на ФОТ",
        unit: "доля",
        type: "number",
        min: 1.302,
        max: 1.302,
        step: 0.001,
        default: 1.302,
        hint: "Страховые взносы, аналогично складу и аэропорту",
      },
      {
        key: "corridorWidthM",
        group: "Безопасность и инфраструктура",
        label: "Ширина основных коридоров",
        unit: "м",
        type: "number",
        min: 1.8,
        max: 3.5,
        step: 0.1,
        default: 2.4,
        hint: "Минимум 1.8 м для AMR с разъездом с каталками — узкие места критичны",
      },
      {
        key: "chargingPowerKw",
        group: "Безопасность и инфраструктура",
        label: "Доступная мощность зарядной инфраструктуры",
        unit: "кВт",
        type: "number",
        min: 15,
        max: 400,
        step: 5,
        default: 80,
        hint: "Обычно у сестринских постов или в технических нишах",
      },
      {
        key: "budgetCapexMRub",
        group: "Экономика",
        label: "Планируемый бюджет на роботизацию (CAPEX)",
        unit: "млн ₽",
        type: "number",
        min: 5,
        max: 200,
        step: 5,
        default: 35,
        hint: "Медицина консервативна — часто начинают с пилота на 1–3 робота",
      },
      {
        key: "horizonYears",
        group: "Экономика",
        label: "Горизонт расчёта TCO",
        unit: "лет",
        type: "number",
        min: 5,
        max: 15,
        step: 1,
        default: 7,
        hint: "ТЗ требует не менее 5 лет",
      },
    ],
  },
};

export const OBJECT_TYPE_LIST = Object.values(OBJECT_TYPES);

export function getObjectType(id) {
  return OBJECT_TYPES[id] ?? null;
}

// Выбранный вариант поля-списка (select) с его числовыми свойствами (speedFactor, slotsPerLane...).
export function selectOption(objectTypeId, key, value) {
  const field = getObjectType(objectTypeId)?.paramSchema.find((f) => f.key === key);
  return field?.options?.find((o) => o.value === value) ?? field?.options?.[0] ?? null;
}

export function defaultParamsFor(objectTypeId) {
  const type = getObjectType(objectTypeId);
  if (!type) return {};

  return Object.fromEntries(
    type.paramSchema.map((field) => [field.key, field.default])
  );
}
